server:
  port: 8040
spring:
  application:
    # 指定Gateway注册到Nacos上的名称
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让Gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-center
          predicates:
            - TimeBetween=上午0:00,下午11:59
            # 配置Gateway要映射到用户中心的uri的地址前缀
            - Path=/users/**
          # 添加一个向发往用户中心的请求上添加Header项的拦截器
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - PreLog=a,b
        - id: content_route
          uri: lb://content-center
          predicates:
            - TimeBetween=上午0:00,下午11:59
            # 配置Gateway要映射到内容中心的uri的地址前缀
            - Path=/shares/**,/admin/**
          # 添加一个向发往内容中心的请求上添加Header项的拦截器
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - PreLog=a,b
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      # 抽样率，默认是0.1(10%)
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
