server:
  port: 8081

spring:
  application:
    # 向Nacos注册服务的时候会使用这个名字
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC&useSSL=false
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
