server:
  port: 8081

spring:
  application:
    # 向Nacos注册服务的时候会使用这个名字
    name: user-center
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定Nacos命名空间id
        #namespace: namespace-id
        # 指定Nacos集群名称
        cluster-name: BJ
        # 指定Nacos元数据,Nacos元数据可用来控制版本，比如内容中心只能调用用户中心的v1版本，不能调用用户中心的v2版本
        #metadata:
        #  instance: c
        #  haha: hehe
        #  version: 1
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC&useSSL=false
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  name-server: 127.0.0.1:9876

JWT_KEY:
  punk1uJWTTokenSecret
JWT_EXPIRE_TIME:
  3600000