server:
  port: 8082

spring:
  application:
    # 向Nacos注册服务的时候会使用这个名字
    name: content-center
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: BJ
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=UTC&useSSL=false
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

# 通过属性配置内容中心访问用户中心的Ribbon负载均衡规则，优先级比UserCenterRibbonConfiguration的代码配置更高
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


# 配置Ribbon加载策略为饥饿加载，提高第一次调用用户中心的速度(默认为延迟加载)，
# clients配置项如果有多个，可以使用逗号分割
ribbon:
  eager-load:
    clients: user-center
logging:
  level:
    tech.punklu.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      # 想要调用的微服务的名称
      user-center:
        loggerLevel: full
