server:
  port: 8082

spring:
  application:
    # 向Nacos注册服务的时候会使用这个名字
    name: content-center
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=UTC&useSSL=false
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

# 通过属性配置内容中心访问用户中心的Ribbon负载均衡规则，优先级比UserCenterRibbonConfiguration的代码配置更高
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
